config/routes.rb
Rails.application.routes.draw do
  root to: 'courses#index'
  devise_for :users
  resource :profile, only: [:show, :new, :create, :edit, :update]
  
  get "up" => "rails/health#show", as: :rails_health_check

  resources :categories do
    resources :courses, only: [:index, :show]
  end

  resources :courses do
    resources :lessons do 
      resources :completed_lessons, only: [:create, :destroy]
    end
    resources :enrollments, except: [:edit, :update, :new]
 
    member do
      get 'certificate', to: 'certificates#show', as: 'certificate'
    end
  end
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light navbar-custom">
  <div class="container">
    <a class="navbar-brand" href="<%= root_path %>">
      <img src="https://www.udemy.com/staticx/udemy/images/v7/logo-udemy.svg" width="91" height="34" alt="Udemy Logo">
    </a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto d-flex align-items-center w-100">  <!-- Allowing flex for right side items -->
        
        <li class="nav-item flex-grow-1">
          <%= form_tag courses_path, method: :get, class: 'd-flex w-100' do %>
            <%= text_field_tag :q, params[:q], placeholder: 'Search...', class: 'form-control me-2 w-100' %>
          <% end %>
        </li>

        <!-- Categories link -->
        <li class="nav-item">
          <a class="nav-link" href="/categories">Categories</a>
        </li>
        
        <% if current_user && current_user.student? %>
          <li class="nav-item">
            <a class="nav-link" href="<%= courses_path %>">Courses</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= courses_path(clicked_my_learning: 'my_learning') %>">My Learning</a>
          </li>
        <% elsif current_user && current_user.instructor? %>
          <li class="nav-item">
            <a class="nav-link" href="<%= courses_path %>">Courses</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= courses_path(clicked_my_courses: 'my_courses') %>">My Courses</a>
          </li>
        <% elsif current_user && current_user.admin? %>
          <li class="nav-item">
            <a class="nav-link" href="<%= courses_path %>">Courses</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= courses_path(clicked_my_learning: 'my_learning') %>">My Learning</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= courses_path(clicked_my_courses: 'my_courses') %>">My Courses</a>
          </li>
        <% end %>
          
        <% if user_signed_in? %>
          <li class="nav-item">
            <a class="nav-link btn-sign-in" href="<%= profile_path(current_user.profile) %>">Profile</a>
          </li>
          <li class="nav-item">
            <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'btn-sign-out nav-link' %>
          </li>
        <% else %>
          <li class="nav-item">
            <a class="nav-link btn-sign-in" href="<%= new_user_session_path %>">Sign In</a>
          </li>
          <li class="nav-item">
            <a class="nav-link btn-sign-up" href="<%= new_user_registration_path %>">Sign Up</a>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OnlineLearningPlatform</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEJ08vYzv8cR+K6z5l0MQ5C6ph/E+0Zlf3cI5xR3UwmYo5FfwA6v9ayHqGTR6" crossorigin="anonymous">
  </head>
  <body>
    <%= render 'layouts/navbar'%>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-QJ5v57+F25Zm5GTr9nXT6t5Jz7D9FrZnld8MZhf6h0Fi6Z5A9GnF37rtuDZJxxD7" crossorigin="anonymous"></script>
  </body>
</html>